<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit

function autoload9fe1ddf3fdbdddc5db245831cb183bd6($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'face' => '/face.php',
            'robot' => '/robot.php',
            'tabletop' => '/tableTop.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload9fe1ddf3fdbdddc5db245831cb183bd6', true);
// @codeCoverageIgnoreEnd
