<?php

CONST ROBOT_FACE_NORTH = 'NORTH';
CONST ROBOT_FACE_SOUTH = 'SOUTH';
CONST ROBOT_FACE_EAST = 'EAST';
CONST ROBOT_FACE_WEST = 'WEST';

CONST COMMAND_PLACE = 'PLACE';
CONST COMMAND_MOVE = 'MOVE';
CONST COMMAND_REPORT = 'REPORT';
CONST COMMAND_DIRECTION_LEFT = 'LEFT';
CONST COMMAND_DIRECTION_RIGHT = 'RIGHT';